import { logout } from '../api/logout';
import { supabase } from '../utils/supabaseClient';

jest.mock('../utils/supabaseClient', () => ({
  supabase: {
    auth: {
      signOut: jest.fn(),
    },
  },
}));

describe('logout api', () => {
  it('calls supabase signOut', async () => {
    (supabase.auth.signOut as jest.Mock).mockResolvedValue({
      error: null,
    });

    await logout();

    expect(supabase.auth.signOut).toHaveBeenCalledTimes(1);
  });
});
//Generated by GitHub Copilot
