import { fireEvent, render, screen } from '@testing-library/react';
import HomePage from '../pages/homePage';
import { logout } from '../api/logout';

jest.mock('../api/logout', () => ({
  logout: jest.fn().mockResolvedValue(undefined),
}));

describe('HomePage Logout', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('renders logout button on the home page', () => {
    render(<HomePage />);

    expect(screen.getByRole('button', { name: /log out/i })).toBeTruthy();
  });

  it('calls logout when the logout button is clicked', () => {
    render(<HomePage />);

    fireEvent.click(screen.getByRole('button', { name: /log out/i }));

    expect(logout).toHaveBeenCalledTimes(1);
  });
});
//Generated by GitHub Copilot
