// settingsPage.test.tsx
// Tests for SettingsPage — structure rendering and password reset button behavior.

import React from 'react';
import '@testing-library/jest-dom';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import SettingsPage from '../pages/settingsPage';
import { supabase } from '../utils/supabaseClient';

// ---------------------------------------------------------------------------
// Mocks
// ---------------------------------------------------------------------------

jest.mock('../utils/supabaseClient', () => ({
  supabase: {
    auth: {
      getUser: jest.fn(),
      resetPasswordForEmail: jest.fn(),
    },
  },
}));

const mockGetUser = supabase.auth.getUser as jest.Mock;
const mockResetPasswordForEmail = supabase.auth.resetPasswordForEmail as jest.Mock;

const EMAIL = 'user@test.com';

// ---------------------------------------------------------------------------
// SettingsPage Tests
// ---------------------------------------------------------------------------

describe('SettingsPage', () => {
  beforeEach(() => {
    mockGetUser.mockResolvedValue({ data: { user: { email: EMAIL } }, error: null });
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  describe('page structure', () => {
    it('renders the page heading and subtitle', () => {
      render(<SettingsPage />);
      expect(screen.getByRole('heading', { name: /settings/i })).toBeInTheDocument();
      expect(screen.getByText(/manage your account settings/i)).toBeInTheDocument();
    });

    it('renders the Account section', () => {
      render(<SettingsPage />);
      expect(screen.getByText(/^account$/i)).toBeInTheDocument();
    });

    it('displays the fetched user email', async () => {
      render(<SettingsPage />);
      expect(await screen.findByText(EMAIL)).toBeInTheDocument();
    });
  });

  describe('Send Reset Link button', () => {
    it('calls resetPasswordForEmail with the user email and correct redirect URL', async () => {
      mockResetPasswordForEmail.mockResolvedValue({ error: null });
      render(<SettingsPage />);
      await screen.findByText(EMAIL);

      await userEvent.click(screen.getByRole('button', { name: /send reset link/i }));

      await waitFor(() => {
        expect(mockResetPasswordForEmail).toHaveBeenCalledWith(EMAIL, {
          redirectTo: `${window.location.origin}/reset-password`,
        });
      });
    });

    it('shows confirmation text after a successful send', async () => {
      mockResetPasswordForEmail.mockResolvedValue({ error: null });
      render(<SettingsPage />);
      await screen.findByText(EMAIL);

      await userEvent.click(screen.getByRole('button', { name: /send reset link/i }));

      expect(
        await screen.findByText(`Reset link sent to ${EMAIL}. Check your inbox.`)
      ).toBeInTheDocument();
    });

    it('shows an error alert when resetPasswordForEmail returns an error', async () => {
      mockResetPasswordForEmail.mockResolvedValue({ error: { message: 'rate limit exceeded' } });
      render(<SettingsPage />);
      await screen.findByText(EMAIL);

      await userEvent.click(screen.getByRole('button', { name: /send reset link/i }));

      expect(await screen.findByText(/failed to send reset link/i)).toBeInTheDocument();
    });

    it('does not call resetPasswordForEmail when email has not loaded', async () => {
      mockGetUser.mockResolvedValue({ data: { user: { email: '' } }, error: null });
      mockResetPasswordForEmail.mockResolvedValue({ error: null });
      render(<SettingsPage />);

      await userEvent.click(screen.getByRole('button', { name: /send reset link/i }));

      expect(mockResetPasswordForEmail).not.toHaveBeenCalled();
    });
  });
});
//Tests generated by Claude Code
